version: "3.9"

services:
  nexu_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    links:
      - postgres
    volumes:
      - .:/home/app
    environment:
      - NODE_ENV=prod
  postgres:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - nexu-data:/data/db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  nexu-data: